args = [
        #SCORE BASED BLACK BOX
        #nattack
        AttrDict({
            "logname": "nattack_eps0.03",
            "attack_name":"nattack",
            "gpu":"2",
            "epsilon": 0.03,
            "norm": np.inf,
            "sample_size": 100,
            "lr":0.02,
            "sigma":0.1,
            "max_queries": 1000
        }),
        #SPSA
        AttrDict({
            "logname":"spsa_l2_0.7",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": 2,
            "eps": 0.7,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }),  
        AttrDict({
            "logname":"spsa_linf_0.03",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": np.inf,
            "eps": 0.03,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }),
        #NES
        AttrDict({
            "logname": "nes_2_eps1",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 1,
            "norm": 2,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 1/100
        }),    
        AttrDict({
            "logname": "nes_linf_0.01",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 0.01,
            "norm": np.inf,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 0.5/100
        }),    
        AttrDict({
            "logname": "nes_linf_0.03",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 0.03,
            "norm": np.inf,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 0.5/100
        }),  
        #WHITEBOX
        #cw
        AttrDict({
            "logname": "cw_kappa0.1",
            "attack_name":"cw",
            "gpu":"2",
            "norm": 2,
            "lr":0.2,
            "kappa":0.1,
            "init_const":0.01,
            "binary_search_steps": 4,
            "max_iter": 50
        }),
        AttrDict({
            "logname": "cw_kappa0",
            "attack_name":"cw",
            "gpu":"2",
            "norm": 2,
            "lr":0.2,
            "kappa":0,
            "init_const":0.01,
            "binary_search_steps": 4,
            "max_iter": 50
        }),
        #deepfool
        AttrDict({
            "logname": "deepfool_l2_overshoot0.005",
            "attack_name":"deepfool",
            "gpu":"2",
            "norm": 2,
            "overshoot":0.005,
            "max_iter":50,
        }),
        AttrDict({
            "logname": "deepfool_l2_overshoot0.01",
            "attack_name":"deepfool",
            "gpu":"2",
            "norm": 2,
            "overshoot":0.1,
            "max_iter":50,
        }),
        AttrDict({
            "logname": "deepfool_l2_overshoot0.02",
            "attack_name":"deepfool",
            "gpu":"2",
            "norm": 2,
            "overshoot":0.2,
            "max_iter":50,
        }),
        AttrDict({
            "logname": "deepfool_l2_overshoot0.03",
            "attack_name":"deepfool",
            "gpu":"2",
            "norm": 2,
            "overshoot":0.3,
            "max_iter":50,
        }),
        #pgd
        AttrDict({
            "logname": "pgd_ce_l2_0.3",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_ce_l2_0.5",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_cw_l2_0.3",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_cw_l2_0.5",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_ce_linf_0.005",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_ce_linf_0.01",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_ce_linf_0.02",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_cw_linf_0.005",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100,
        }),
        AttrDict({
            "logname": "pgd_cw_linf_0.01",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100,
            }),
        AttrDict({
            "logname": "pgd_cw_linf_0.02",
            "attack_name": "pgd",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100,
            }),   
        #mim
        AttrDict({
            "logname": "mim_ce_l2_0.3",
            "attack_name": "mim",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_ce_l2_0.5",
            "attack_name": "mim",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_cw_l2_0.3",
            "attack_name": "mim",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_cw_l2_0.5",
            "attack_name": "mim",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_ce_linf_0.005",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_ce_linf_0.01",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_ce_linf_0.02",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_cw_linf_0.005",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100,
            "decay_factor": 1.0,
        }),
        AttrDict({
            "logname": "mim_cw_linf_0.01",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100,
            "decay_factor": 1.0,
            }),
        AttrDict({
            "logname": "mim_cw_linf_0.02",
            "attack_name": "mim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100,
            "decay_factor": 1.0,
            }),   
        #bim
        AttrDict({
            "logname": "bim_ce_l2_0.3",
            "attack_name": "bim",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_ce_l2_0.5",
            "attack_name": "bim",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_cw_l2_0.3",
            "attack_name": "bim",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.3,
            "stepsize": 2.5*0.3/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_cw_l2_0.5",
            "attack_name": "bim",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.5,
            "stepsize": 2.5*0.5/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_ce_linf_0.005",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_ce_linf_0.01",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_ce_linf_0.02",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_cw_linf_0.005",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.005,
            "stepsize": 0.005/100,
            "steps": 100
        }),
        AttrDict({
            "logname": "bim_cw_linf_0.01",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.01,
            "stepsize": 0.01/100,
            "steps": 100
            }),
        AttrDict({
            "logname": "bim_cw_linf_0.02",
            "attack_name": "bim",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.02,
            "stepsize": 0.02/100,
            "steps": 100
            }),   
        #fgsm
        AttrDict({
            "logname": "fgsm_ce_l2_0.3",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.3
        }),
        AttrDict({
            "logname": "fgsm_ce_l2_0.5",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":2,
            "loss": "ce",
            "eps": 0.5
        }),
        AttrDict({
            "logname": "fgsm_cw_l2_0.3",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.3
        }),
        AttrDict({
            "logname": "fgsm_cw_l2_0.5",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":2,
            "loss": "cw",
            "eps": 0.5
        }),
        AttrDict({
            "logname": "fgsm_ce_linf_0.005",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.005
        }),
        AttrDict({
            "logname": "fgsm_ce_linf_0.01",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.01
        }),
        AttrDict({
            "logname": "fgsm_ce_linf_0.02",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "ce",
            "eps": 0.02
        }),
        AttrDict({
            "logname": "fgsm_cw_linf_0.005",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.005
        }),
        AttrDict({
            "logname": "fgsm_cw_linf_0.01",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.01
            }),
        AttrDict({
            "logname": "fgsm_cw_linf_0.02",
            "attack_name": "fgsm",
            "gpu": "2",
            "norm":np.inf,
            "loss": "cw",
            "eps": 0.02
            }),   

        AttrDict({
            "logname": "nattack_eps0.03",
            "attack_name":"nattack",
            "gpu":"2",
            "epsilon": 0.03,
            "norm": np.inf,
            "sample_size": 100,
            "lr":0.02,
            "sigma":0.1,
            "max_queries": 2000
        }),
        AttrDict({
            "logname": "nattack_eps0.05",
            "attack_name":"nattack",
            "gpu":"2",
            "epsilon": 0.05,
            "norm": np.inf,
            "sample_size": 100,
            "lr":0.02,
            "sigma":0.1,
            "max_queries": 2000
        }),
        AttrDict({
            "logname": "nattack_eps0.1",
            "attack_name":"nattack",
            "gpu":"2",
            "epsilon": 0.1,
            "norm": np.inf,
            "sample_size": 100,
            "lr":0.02,
            "sigma":0.1,
            "max_queries": 2000
        }),
        #SPSA
        AttrDict({
            "logname":"spsa_l2_0.5",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": 2,
            "eps": 0.5,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }), 
        AttrDict({
            "logname":"spsa_l2_1.0",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": 2,
            "eps": 1.0,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }), 
        AttrDict({
            "logname":"spsa_linf_0.01",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": np.inf,
            "eps": 0.01,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }),
        AttrDict({
            "logname":"spsa_linf_0.02",
            "attack_name":"spsa",
            "gpu":"2",
            "norm": np.inf,
            "eps": 0.02,
            "learning_rate":0.01,
            "delta":0.01,
            "spsa_samples":10,
            "sample_per_draw": 20,
            "max_queries": 2000
        }),
        #NES
        AttrDict({
            "logname": "nes_2_eps0.7",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 0.7,
            "norm": 2,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 1/100
        }),    
        AttrDict({
            "logname": "nes_2_eps1.3",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 1.3,
            "norm": 2,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 1/100
        }),
        AttrDict({
            "logname": "nes_linf_0.05",
            "attack_name":"nes",
            "gpu":"2",
            "epsilon": 0.05,
            "norm": np.inf,
            "nes_samples": 10,
            "nes_per_draw":20,
            "max_queries": 2000,
            "stepsize": 0.5/100
        }),
    ]